INSERT INTO PERSON (ID,NAME,LOCATION,BIRTH_DATE)
VALUES(10001,'VAIBHAV SOOD','DELHI', sysdate());


INSERT INTO PERSON (ID,NAME,LOCATION,BIRTH_DATE)
VALUES(10002,'VAIBHAV SOOD 2','DELHI', sysdate());


INSERT INTO PERSON (ID,NAME,LOCATION,BIRTH_DATE)
VALUES(10003,'VAIBHAV SOOD 3','DELHI', sysdate());


INSERT INTO PERSON (ID,NAME,LOCATION,BIRTH_DATE)
VALUES(10004,'VAIBHAV SOOD 4 ','DELHI', sysdate());
